### ISSUE TITLE
can't open putty

### ISSUE THREAD

**Issue by NuxLO49** [CirqueiraDev/KryptonC2#1]
do you have any suggestions? i have followed the tutorial well using raw connection also in puty and the port is set.

**Comment by lxntagram** [comment]
You should also provide a log

**Comment by NuxLO49** [comment]
> You should also provide a log

what does that mean? can you show me how?

**Comment by lxntagram** [comment]
Can you upload a video trying to connect?

**Comment by CirqueiraDev** [comment]
Yes

**Comment by NuxLO49** [comment]
solved. thanks for the video tutorial and the update. hopefully in the future more frequent updates.
